[project]
name = "mtg-elt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt>=1.0.0.38.35",
    "dbt-duckdb>=1.9.2",
    "duckdb>=1.2.1",
    "pre-commit>=4.2.0",
    "pylint>=3.3.6",
    "ruff>=0.11.2",
]
